### ISSUE TITLE
Tinkerfite: Weapon damage multiplier should only scale every 400 AR up to 1000 AR

### ISSUE THREAD

**Issue by jroovers** [TheTinkeringIdiot/Tinkerplants#35]
Hi TTI,

First off, thanks for making these tools! I use them (almost) daily. 

When looking at higher level stats (beyond 1k AR) I noticed the Tinkerfite calculator was a bit too optimistic, which prompted to look a bit into how the damage is calculated. So I did some reading at, presumely the same source you used, AO Universe: https://www.ao-universe.com/guides/classic-ao/gameplay-guides-6/attack-rating-weapon-damage-and-special-attacks

There it is written that below 1k AR, damage scales by 1x your weapon damage for every 400 skills
Above 1k AR, damage scales 1x your weapon damage for every 1200 skill (... _roughly_).

TinkerFite uses these numbers too but the first part of the calculation is not capped to 1k skill.
This is the code in question:

```python
    ar_bonus = 1 + (atk_skill / 400)
    if atk_skill > 1000:
        ar_bonus += (atk_skill - 1000) / 1200
```
So for 2500 skill:
```python
ar_bonus = 1 + 2500 / 400 # 7.25
if skill > 1000:
  ar_bonus += 1500 / 1200 # 1.25
# total 8.50, too optimistic
```

I think the fix is capping the first part of the calculation to 1000 skill

```python
    ar_bonus = 1 + (min(atk_skill, 1000) / 400)
    if atk_skill > 1000:
        ar_bonus += (atk_skill - 1000) / 1200
```

So again for 2500 skill:
```python
ar_bonus = 1 + min(2500, 1000) / 400 # 3.5
if skill > 1000:
  ar_bonus += 1500 / 1200 # 1.25
# total 4.75
```

Code in question:
https://github.com/TheTinkeringIdiot/Tinkerplants/blob/e036aa123ac122434facda693cd942d1509ffba3/tinkerfite/views.py#LL418C10-L418C10

**Comment by TheTinkeringIdiot** [comment]
Good catch! That's definitely a bug. Thanks for the head's up!

I've patched and deployed, it should be live. 

This calculation is likely still too optimistic (though much more accurate for what we know about damage calculation in the game). There are various reports that later patches/expansions introduced another AR breakpoint around 1700. However, there is no current consensus on what post-1700 AR breaks _to_, and what testing has been done indicates that it may even include per-profession scaling past that point, with even more breakpoints past 2000. With that lack of firm information, it's difficult to make Tinkerfite perfectly accurate, but you've definitely helped make it better. Thank you!
